---
- name: install apache
  hosts: all
  become: false
  gather_facts: false
  tasks:
  - name: "install apache"
    package: name=httpd state=present 
  - name: start apache
    service: name=httpd state=started
  - name: wait 30 secs
    pause: seconds=30
  - name: stop apache
    service: name=httpd state=stopped
...
